[package]
name = "nes"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "crates/cpu",
  "crates/memory",
  "crates/rom",
]

[dependencies]
cpu = { path = "crates/cpu" }
memory = { path = "crates/memory" }
rom = { path = "crates/rom" }
