[package]
name = "nes"
version = "0.1.0"
edition = "2018"

[workspace]
members = [
  "crates/cpu",
  "crates/memory",
]

[dependencies]
cpu = { path = "crates/cpu" }
memory = { path = "crates/memory" }